//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComposerAdmin.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComposerAdmin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a About {0}.
        /// </summary>
        internal static string ABOUT_FORM_ABOUT {
            get {
                return ResourceManager.GetString("ABOUT_FORM_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Version {0}.
        /// </summary>
        internal static string ABOUT_LABEL_VERSION {
            get {
                return ResourceManager.GetString("ABOUT_LABEL_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ApplicationIcon {
            get {
                object obj = ResourceManager.GetObject("ApplicationIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Desktop Composition Files |*.dcxml|All files (*.*)|*.*.
        /// </summary>
        internal static string COMPOSITION_FILE_FILTER {
            get {
                return ResourceManager.GetString("COMPOSITION_FILE_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New Composition File.
        /// </summary>
        internal static string FILE_NEW_LABEL {
            get {
                return ResourceManager.GetString("FILE_NEW_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Path Not Found.
        /// </summary>
        internal static string MESSAGE_PATH_NOT_FOUND {
            get {
                return ResourceManager.GetString("MESSAGE_PATH_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Document contains unsaved Changes. Do you want to save?.
        /// </summary>
        internal static string MESSAGE_PROMPT_SAVE {
            get {
                return ResourceManager.GetString("MESSAGE_PROMPT_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The Path was not found or Access is Denied.
        /// </summary>
        internal static string MESSAGE_TITLE_PATH_NOT_FOUND {
            get {
                return ResourceManager.GetString("MESSAGE_TITLE_PATH_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confirm Save.
        /// </summary>
        internal static string MESSAGE_TITLE_SAVE {
            get {
                return ResourceManager.GetString("MESSAGE_TITLE_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Done.
        /// </summary>
        internal static string STATUSMSG_DONE {
            get {
                return ResourceManager.GetString("STATUSMSG_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Importing Menu Structure....
        /// </summary>
        internal static string STATUSMSG_IMPORTING_MENUSTRUCTURE {
            get {
                return ResourceManager.GetString("STATUSMSG_IMPORTING_MENUSTRUCTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Maximized.
        /// </summary>
        internal static string WINDOWMODE_MAXIMIZED {
            get {
                return ResourceManager.GetString("WINDOWMODE_MAXIMIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Minimized.
        /// </summary>
        internal static string WINDOWMODE_MINIMIZED {
            get {
                return ResourceManager.GetString("WINDOWMODE_MINIMIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Normal.
        /// </summary>
        internal static string WINDOWMODE_NORMAL {
            get {
                return ResourceManager.GetString("WINDOWMODE_NORMAL", resourceCulture);
            }
        }
    }
}
