; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Desktop Composer Agent"
#define MyAppProductName "ComposerAgent"
#define MyAppVersion "0.9.2"
#define MyAppVersionText "0.9"
#define MyAppPublisher "Sequence Software"
#define MyAppAuthor "Riccardo Bicelli"
#define MyAppURL "https://github.com/rbicelli/DesktopComposer"
#define MyAppExeName "ComposerAgent.exe"
#define MyAppDescription "Desktop Composition Agent"
#define MyAppGroupName "Desktop Composer"


[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{46D19B75-D181-46EE-B688-204C5FC19A2E}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={commonpf}\Sequence Software\Composer Agent
DefaultGroupName={#MyAppGroupName}
OutputBaseFilename=ComposerAgentSetup-{#MyAppVersion}
Compression=lzma
SolidCompression=yes
AppCopyright={#MyAppPublisher} 2020
AllowUNCPath=False
UninstallDisplayName={#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
VersionInfoVersion={#MyAppversion}
VersionInfoCompany={#MyAppPublisher}
VersionInfoDescription={#MyAppDescription}
VersionInfoTextVersion={#MyAppVersiontext}
VersionInfoCopyright=2020 {#MyAppAuthor}
VersionInfoProductName={#MyAppProductName}
VersionInfoProductVersion={#MyAppVersion}
VersionInfoProductTextVersion={#MyAppVersiontext}
MinVersion=0,6.0
ArchitecturesInstallIn64BitMode=x64
LicenseFile=..\LICENSE

[Files]
Source: "..\ComposerAgent\bin\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion; MinVersion: 0,6.1
Source: "..\ComposerAgent\bin\Release\DesktopComposer.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\ComposerAgent\bin\Release\IconLib.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\ComposerAgent\bin\Release\IconLib.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\LICENSE"; DestDir: "{app}"; Flags: ignoreversion

[Run]
Filename: "{app}\ComposerAgent.exe"; Parameters: "-install -noconsole"; WorkingDir: "{app}"; Flags: postinstall runhidden

[UninstallRun]
Filename: "{app}\ComposerAgent.exe"; Parameters: "-uninstall -noconsole"; WorkingDir: "{app}"; Flags: runhidden
