; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{46D19B75-D181-46EE-B688-204C5FC19A2E}}
AppName=Desktop Composer Agent
AppVersion=1.0
AppPublisher=Sequence Software
AppPublisherURL=http://www.sequence.it/desktopcomposer
AppSupportURL=http://www.sequence.it/desktopcomposer
AppUpdatesURL=http://www.sequence.it/desktopcomposer
DefaultDirName={commonpf}\Sequence Software\Composer Agent
DefaultGroupName=Desktop Composer
OutputBaseFilename=ComposerAgent-Setup
Compression=lzma
SolidCompression=yes

[Files]
Source: "..\ComposerAgent\bin\Release\ComposerAgent.exe"; DestDir: "{app}"; Flags: ignoreversion; MinVersion: 0,6.1
Source: "..\ComposerAgent\bin\Release\DesktopComposer.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\ComposerAgent\bin\Release\IconLib.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\ComposerAgent\bin\Release\IconLib.xml"; DestDir: "{app}"; Flags: ignoreversion

[Run]
Filename: "{app}\ComposerAgent.exe"; Parameters: "-install -noconsole"; WorkingDir: "{app}"; Flags: postinstall runhidden; Description: "Install Composer Agent"

[UninstallRun]
Filename: "{app}\ComposerAgent.exe"; Parameters: "-uninstall -noconsole"; WorkingDir: "{app}"; Flags: runhidden
